name: Integration test build for activity API

on:
  push:
    branches:
      - main
  workflow_dispatch:
  #schedule:
   # - cron: "53 14 * * *"

jobs:
  run-tests:
    runs-on: ubuntu-latest

  # Clone/Checkout the project
  # Setup the python
  # Install all the dependencies which are in the requirements.txt
  # pytest with html options
  # Check if tests are success or failure and upload the test report

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          
      - name: Run Integration Tests
        run: |
          pytest
      
      - name: Upload Html Test Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: ./reports/report*.html

  build-image:
    needs: run-tests

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: |
          docker build -t apitesting .

      - name: Run local Image
        run: |
          docker run apitesting
